### ISSUE TITLE
Weird display behavior in small width REPL

### ISSUE THREAD

**Issue by gdalle** [FedeClaudi/Term.jl#134]
Hi, and thanks for the awesome package!

In VSCode my REPL is usually quite narrow, and this seems to mess Term up. Is there something I failed to configure appropriately?

The following screenshots show what happens when I try to display the following function with different terminal widths.
```julia
julia> dumb_function(x, y) = x + y
```
Sufficient width:
![Screenshot from 2022-07-05 14-54-57](https://user-images.githubusercontent.com/22795598/177333225-72777331-7bee-4862-985a-987bb5c2a1c5.png)
Insufficient width:
![Screenshot from 2022-07-05 14-54-42](https://user-images.githubusercontent.com/22795598/177333239-c945efb3-d994-4687-8f63-20c2d157f716.png)

**Comment by FedeClaudi** [comment]
Thanks for reporting this, and sorry for the delay with getting back to you. 
There was an error with how the panel's content was handled when creating such a narrow panel. 
It will be fixed in the next release:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/17436313/181997269-2a313507-9935-4c57-a38c-459a85250ce1.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/17436313/181997286-f8ccad33-5aed-43fd-aed4-777aaadcffde.png">


Though it might still create aberrant output for very narrow layouts: reshaping text with lots of markup/ansi style info is not trivial and gets increasingly complicated the narrow the lines are 😓
