### ISSUE TITLE
ProgressJob for Panels

### ISSUE THREAD

**Issue by VarLad** [FedeClaudi/Term.jl#149]
It would be awesome if we could use Panels in ProgressJobs. That would allow for some neat animations.
@FedeClaudi Can this be done with current Term.jl?

**Comment by FedeClaudi** [comment]
Hey, 

Not sure what ProgressJobs is? Have you got a link?

As mentioned in https://github.com/FedeClaudi/Term.jl/issues/143, there's no well developed "animation" functionality in Term.jl - yet. But the basic principle is to print what you need, clear the terminal and print out the updated version. 

```julia
using Term
import Term.Consoles: clear

make_p(i) = Panel("Iteration $i", fit=true)

for i in 1:10
    clear()
    make_p(i) |> print
    sleep(1)
end
```

If `make_p` is slow, or the call to `print` takes a while`, you can first create what you want and then clear and print
```julia
using Term
import Term.Consoles: clear

make_p(i) = Panel("Iteration $i", fit=true)

for i in 1:10
    content = make_p(i) |> string
    clear()
    print(content)
    sleep(1)
end
```

or even use an `IOBuffer`. 


Hope this helps, let me know otherwise.

**Comment by VarLad** [comment]
By ProgressJob I was referring to this https://fedeclaudi.github.io/Term.jl/dev/adv/progressbars/#ProgressJob

**Comment by VarLad** [comment]
@FedeClaudi The above works too. My only complain being, can I do it in a "continuous manner" like how ProgressBar works?
The above syntax leaves a big space when printing. ProgressBars update without leaving spaces

**Comment by FedeClaudi** [comment]
my bad, I thought you were referring to another package haha. 

Yeah so the progress bar does some fancy stuff:
- first, it does the clear/print stuff in a buffer and then dumps that into `stdout`, That makes it more "atomic" so you don't see refreshing artifacts
- Instead of clearing the whole console, it moves the cursor to the first line of progress bars, clears that line only, moves to the next, clears it...  So only the lines that make up the progress bars get updated, leaving the above clean. This is obviously hard because you need to know where the cursor is, where you need to go, which lines to clear....


At some point Term will offer some functionality to automate all of this, but in the meanwhile:

```julia
using Term

using Term.Consoles
import Term: CODES_16BIT_COLORS


function animation()
    # clear()
    iob = IOBuffer()  # buffer

    col = "default"
    p = nothing
    for i in 1:100
        # erase previous panel, one line at the time
        i > 1 && begin
            nlines = p.measure.h
            for ln in 1:nlines
                up(iob)
                erase_line(iob)
            end
        end

        # print the new panel 
        i % 10 == 0 && (col = rand(CODES_16BIT_COLORS).first)
        p = Panel("$i{bold white}/100{/bold white}", justify=:center, width=60, style=col) 
        print(iob, p)
        
        # dump buffer on stdout
        print(String(take!(iob)))

        # sleep
        sleep(.02)
    end
end


animation()
animation()
```


This should work for any renderable you want to animate, though it will break if you call any `print` statements during the animation.

**Comment by VarLad** [comment]
@FedeClaudi This is perfect. Although it breaks when I multiply two panels. Any idea why does that happen?

**Comment by FedeClaudi** [comment]
It seems to be an issue with using the `IOBuffer`, this works (printing to `iob=stdout`):


```julia
using Term

using Term.Consoles
import Term: CODES_16BIT_COLORS


function animation()
    # clear()
    iob = IOBuffer()  # buffer
    iob = stdout

    col = "default"
    p = nothing
    for i in 1:100
        # erase previous panel, one line at the time
        i > 1 && begin
            nlines = p.measure.h
            for ln in 1:nlines
                up(iob)
                erase_line(iob)
            end
        end

        # print the new panel 
        i % 10 == 0 && (col = rand(CODES_16BIT_COLORS).first)

        p = content(i, col)

        print(iob, p)

        # dump buffer on stdout
        # print(String(take!(iob)))

        # sleep
        sleep(.02)
    end
end


function content(i::Int, col::String)
    p = Panel(
        "$i{bold white}/100{/bold white}",
        justify=:center,
        width=60,
        style=col) 
    return if 20 < i < 50
        p / p
    else
        p * p
    end
end

animation()
```

The offending line is `print(iob, p)` for `iob=IOBuffer()`. If you replace it with `println(iob, string(p))`.
Using Term's `@showme` to see what gets called between the two versions of this line:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/17436313/187079237-760600b7-8f25-4256-b395-6fc72b17437a.png">

vs

<img width="745" alt="image" src="https://user-images.githubusercontent.com/17436313/187079273-b66ab958-320a-450c-9f72-1ce6c26689bb.png">

The first call's Term's print method which uses `console_width` to reshape the output to have the right size. `console_width(IOBuffer()) = 80` so for a large renderables like two panels side by side the layout gets broken up over two lines. I'm not sure if you can tell IOBuffer to have a different size, I'd like to know that, but it the meanwhile you can use `println(iob, string(p))` or `write(stdout, take!(iob))` to dump the output to stdout without reshaping.

**Comment by FedeClaudi** [comment]
So, this issue led me through a bit of a rabbit hole...

https://user-images.githubusercontent.com/17436313/187095828-de499014-6c9c-4ee1-9397-4fdbfd9a6ac5.mov

I'll be working on "live" renderables next, see development at: https://github.com/FedeClaudi/Term.jl/blob/LIVE/src/live.jl

**Comment by FedeClaudi** [comment]
Hey I'll close this issue as I think you've got all you need for now, stay tuned for a release.
Feel free to re-open if you need anything.
