### ISSUE TITLE
Representing QR codes in Julia terminal?

### ISSUE THREAD

**Issue by jbytecode** [FedeClaudi/Term.jl#151]
I am so sorry if I am bothering someone but I am opening this issue due to the discussion on Twitter:

https://twitter.com/mhsatman/status/1563975585948483585

The main question is:

Is it possible to represent a QR  code in Julia terminal using its ASCII equivalents? It may be useful if it was possible.

Thank you in advance.

**Comment by FedeClaudi** [comment]
Here you go!

<img width="571" alt="image" src="https://user-images.githubusercontent.com/17436313/187096778-7bca4268-6872-4a39-ae5a-c3f6eb0beff4.png">

I've created an [example](https://github.com/FedeClaudi/Term.jl/blob/QR/examples/QR_renderable.jl) on how to create a custom `AbstractRenderable` subtype for a QR code visualization starting from a `BitMatrix`.
It takes advantage of the half block character (U+02580) ▄ (see https://docs.julialang.org/en/v1/manual/unicode-input/) and different foreground/background colors to create "squared pixels" which would be otherwise hard to get in the terminal (the aspect ratio of terminal line's is not square). 

This could be improved (besides using a proper QR code generator) to "scale" the visualization such that one pixel in the `BitMatrix` corresponds to an `nxn` square in the renderable, but its a good start. 

By changing the way `qr` is created you can also do bar codes:
```julia
qr = fill(0, (10, 100))
idxs = rand(1:100, 50)
qr[:, idxs] .= 1
qr = BitMatrix(qr)
```

<img width="636" alt="image" src="https://user-images.githubusercontent.com/17436313/187097194-85f94340-3a04-40eb-a531-35e16541e87a.png">



Hope this helps!

**Comment by jbytecode** [comment]
Great! Thank you.
