### ISSUE TITLE
Clarification of "Only for Developers" advice

### ISSUE THREAD

**Issue by TorkelE** [FedeClaudi/Term.jl#176]
Hello,
I have been meaning to get some good error printout thing, and Term seemed like a possibility. However, I found this warning:
![image](https://user-images.githubusercontent.com/18099310/206286472-e038411e-62f4-4540-9f39-aaa1cc6e635f.png)
Exactly under what circumstances do, I have to worry about this?

I do a decent about pf package development within SciML, and don't want to mess things up there. Is it unless I actively try to integrate this fro errors in my packages, it will be fine, and I can just install it in my local environment? Or should I be careful here as well
(sorry, I am not super savvy when it comes to Julia dev stuff)

**Comment by FedeClaudi** [comment]
Hey, 

The idea with term's `repr` and `stacktraces` functionality is that you overwrite function's that are normally defined in `Base`, the default library. If you just do that in your local environment (e.g. through yuou `startup.jl`), that's fine. You'll see the effects of using Term, but when you release your package to others they won't be affected by it.

However, if you, say, call `install_term_stacktrace` in your package, then any user of that package will also have `Term` overwrite the error-handling code in `Base`. Your users may not want that (e.g. they use other packages to do stuff with stacktraces), but by you inserting that in your code you're imposing it on them. 

Hope that makes it clearer, but let me know otherwise.

**Comment by TorkelE** [comment]
Great, I will define it in `startup.jl` then and leave it there. Just wanted to ensure I didn't cause a major mess-up for many people... Thanks for the quick answer!
