### ISSUE TITLE
Precompilation code causes deadlock

### ISSUE THREAD

**Issue by andreasnoack** [FedeClaudi/Term.jl#190]
I've had issues with this package hanging during precompilation. My colleague @vtjnash said about https://github.com/FedeClaudi/Term.jl/blob/e58f28bb19e977bc63e76c848e37144356267b75/src/Term.jl#L175-L192

that

> I am not sure you are allowed to alter stdout during precompile. But regardless, making it unread creates a deadlock

and that similar issues apply to the version on master.

**Comment by FedeClaudi** [comment]
Thanks for getting in touch. This hasn't been a problem in my experience, including in CI on various OS. Could you give me more details about your setup and what's happening please?

**Comment by ronisbr** [comment]
Hi! I saw this problem before when something caused an unexpected behavior inside the precompilation calls, which is not seen due to the stdout redirection. It can be some error that is not printed to stderr or some request for user input. This assumption can be verified by removing all lines related to redirection and trying to recompile the package.

**Comment by FedeClaudi** [comment]
thanks!

**Comment by FedeClaudi** [comment]
Thank you both for the input. I will edit the precompilation code to remove the need for this.
