### ISSUE TITLE
String Perf traps and invalidations

### ISSUE THREAD

**Issue by miguelraz** [FedeClaudi/Term.jl#45]
I love this repo!

But there's some easy perf steps to implement without too much hassle [if you read the manual](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-string-interpolation-for-I/O)

Some of the trickier ones (but hoo boy, taking like 5s to print the `make_logo` :/ ) [can also be found here](https://timholy.github.io/SnoopCompile.jl/stable/snoopr/#invalidations) - they should help out a ton for many of the use cases that you are using.

**Comment by FedeClaudi** [comment]
Thanks!

There's lots of room for optimization 😬 

The goal so far was to get together a working, minimal, features set for people to start using Term. 
Now I was planning to spend some time cleaning up the code and improving performance.

I'll have a look at the links you've sent, but if you have any advice on profiling/optimization practices that would help a lot, it's not something I've spent a lot of time doing in Julia yet.

**Comment by FedeClaudi** [comment]
I'm surprised it took so long though, `print(make_logo())` should be pretty fast:
![image](https://user-images.githubusercontent.com/17436313/159059455-14e7b243-3054-42f1-beb1-b662e6c835c4.png)

**Comment by FedeClaudi** [comment]
https://github.com/FedeClaudi/Term.jl/pull/60 introduces substantial changes that reduce runtime and allocations. Pre-compilation still takes a few seconds. I'm happy to make changes if you have suggestions for that.

**Comment by FedeClaudi** [comment]
> I don't want to backseat drive 

Not at all, this is very useful. 

1. macros are used very sparingly in Term. Term exposes a bunch of styling macros for quick use, but I expect that most users will be using the `[style] markup syntax [/style]` instead.
> ... there's too many macros being used where plain functions could be used instead

Have you got any specific spot in place? 

2. I think I understand what you mean. Instead of "injecting" the style codes in the string,  keep track of where they should appear when you stream stuff to the IO buffer. That's very clever.

After your initial issue I've spent a bunch time cleaning up the code and now the style parsing is more efficient:
```Julia
pts = """Lorem[red] ipsum dolor s[/red]it amet, consectetur adipiscing elit,
ed do eiusmod tempor [bold blue]incididu[underline]nt ut labore et dolore magna aliqua. Ut enim ad minim
 veniam, quis nos[/underline]trud exercitation ullamco laboris nisi ut aliquip ex 
 ea commodo consequat. Duis aute [/bold blue][red on_black]irure dolor in reprehenderit 
 in voluptate velit esse cillum dolore eu fugiat nulla 
 pariatur. Excepteur sint occaecat[/red on_black] cupidatat non proident, 
 sunt in [green]culpa qui officia[/green] deserunt mollit anim 
 id est laborum."""

@time apply_style(pts);  # 0.000245 seconds (412 allocations: 37.781 KiB)
```

200ns is not great, surely what you suggest would be faster. The problem is that as you hint to, I need to cut and stitch together the whole string a bunch of times and that takes allocations. I get screwed over by the fact that strings are immutable in Julia. I've considered working with vectors of `Char`s instead, but not sure if that would make it any better.

> You then iterate in tandem on the original string and the bookkeeping vector/structure, and where the control codes need to be emitted that prints out to the proper IO buffer.

The challenge with this approach is that you still need to remove the markup style tags `[]..[/]` from the string, so you still end up doing a bunch of strings cutting. Also that means that once you've cut out one tag the position of the following codes changes... it gets messy. 

-----

I guess one thing worth mentioning is that I don't see Term processing huge amounts of text. It's to produce nice output for humans and there's only so much reading a human can do. The styling part is also one of the most expensive parts. So it's mostly about sparingly producing nice terminal output in you code and it would likely add a few milliseconds to runtime. It's still worth improving performance, especially when dealing with things like progressbars that are refreshed at 60Hz, but it might not be worth obsessing over it (for now). 

> Huge fan and I can't wait to see what comes next.

Thanks! I'm looking forward to see what you make of it!. For the time being it will be mostly about performance improvements and bug fixes, but in the future I will start adding new features like `Table`s.

**Comment by FedeClaudi** [comment]
By the way I did do a lot of work to improve performance (it will come with the next release). Benchmarking `print_logo` went from
![image](https://user-images.githubusercontent.com/17436313/161230625-3e8f722d-6f65-4101-a495-8d62585260c9.png)


to

![image](https://user-images.githubusercontent.com/17436313/161230604-854c9e22-8659-4321-8bc7-10f6b0a79b22.png)

a 45x speed up and a 10x reduction in allocations.
