### ISSUE TITLE
Term removes bracket `[...]`

### ISSUE THREAD

**Issue by YongHee-Kim** [FedeClaudi/Term.jl#84]
```julia
julia> x = Term.RenderableText("This and that [something] for")
RenderableText <: AbstractRenderable size: Measure (w: 18, h: 1)

julia> print(x)
This and that  for
```
`[]` is being removed when `apply_style` function is called 
https://github.com/FedeClaudi/Term.jl/blob/39fc5ec8351bd905349abb23e5395b195ccfccbb/src/renderables.jl#L98

**Comment by FedeClaudi** [comment]
hey, is this with the most recent version?

**Comment by YongHee-Kim** [comment]
Yes I'm on `0.3.0`

**Comment by FedeClaudi** [comment]
mmm, I thought I had fixed this. WIll look into it ASAP, thank's for letting me know.

**Comment by YongHee-Kim** [comment]
No need to hurry😄thank you for amazing package!

**Comment by FedeClaudi** [comment]
Hey, 

So last time I replied in a rush and misunderstood the situation.
This is expected behavior, single `[...]` are treated as markup style tags and removed from the text output. If you want your text to display squared brackets you need to use double brackets:

```Julia
julia> print(Term.RenderableText("This and that [[something]] for"))
This and that [something] for
```

I've added a [disclaimer](https://fedeclaudi.github.io/Term.jl/dev/basics/styled_text/) in the docs to warn people about this behavior. 

P.s.: I'm guessing some people would prefer if single brackets were ignored when they don't contain style information, but that has two downsides:
1. if you had a typo in your style tag (`[reds]`) it'd be nicer if that was just ignored
2. more importantly, if you want to write `[red]` you wouldn't be able to. With the current behavior `[[red]]` works.
